SMS/src/java/entities/Poruke.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package entities;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;

/**
 *
 * @author Grupa2
 */
@Entity
@Table(name = "poruke")
@XmlRootElement
@NamedQueries({
    @NamedQuery(name = "Poruke.findAll", query = "SELECT p FROM Poruke p")
    , @NamedQuery(name = "Poruke.findById", query = "SELECT p FROM Poruke p WHERE p.id = :id")
    , @NamedQuery(name = "Poruke.findByTekst", query = "SELECT p FROM Poruke p WHERE p.tekst = :tekst")})
public class Poruke implements Serializable {

    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Basic(optional = false)
    @Column(name = "id")
    private Integer id;
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 45)
    @Column(name = "tekst")
    private String tekst;
    @JoinColumn(name = "roditelji_id", referencedColumnName = "id")
    @ManyToOne(optional = false)
    private Roditelji roditeljiId;
    @JoinColumn(name = "ucitelji_id", referencedColumnName = "id")
    @ManyToOne(optional = false)
    private Ucitelji uciteljiId;

    public Poruke() {
    }

    public Poruke(Integer id) {
        this.id = id;
    }

    public Poruke(Integer id, String tekst) {
        this.id = id;
        this.tekst = tekst;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getTekst() {
        return tekst;
    }

    public void setTekst(String tekst) {
        this.tekst = tekst;
    }

    public Roditelji getRoditeljiId() {
        return roditeljiId;
    }

    public void setRoditeljiId(Roditelji roditeljiId) {
        this.roditeljiId = roditeljiId;
    }

    public Ucitelji getUciteljiId() {
        return uciteljiId;
    }

    public void setUciteljiId(Ucitelji uciteljiId) {
        this.uciteljiId = uciteljiId;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (id != null ? id.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Poruke)) {
            return false;
        }
        Poruke other = (Poruke) object;
        if ((this.id == null && other.id != null) || (this.id != null && !this.id.equals(other.id))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "entities.Poruke[ id=" + id + " ]";
    }
    
}

SMS/src/java/entities/Ucitelji.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package entities;

import java.io.Serializable;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 *
 * @author Grupa2
 */
@Entity
@Table(name = "ucitelji")
@XmlRootElement
@NamedQueries({
    @NamedQuery(name = "Ucitelji.findAll", query = "SELECT u FROM Ucitelji u")
    , @NamedQuery(name = "Ucitelji.findById", query = "SELECT u FROM Ucitelji u WHERE u.id = :id")
    , @NamedQuery(name = "Ucitelji.findByIme", query = "SELECT u FROM Ucitelji u WHERE u.ime = :ime")
    , @NamedQuery(name = "Ucitelji.findByPrezime", query = "SELECT u FROM Ucitelji u WHERE u.prezime = :prezime")})
public class Ucitelji implements Serializable {

    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Basic(optional = false)
    @Column(name = "id")
    private Integer id;
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 45)
    @Column(name = "ime")
    private String ime;
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 45)
    @Column(name = "prezime")
    private String prezime;
    @OneToMany(cascade = CascadeType.ALL, mappedBy = "uciteljiId")
    private List<Odeljenja> odeljenjaList;
    @OneToMany(cascade = CascadeType.ALL, mappedBy = "uciteljiId")
    private List<Poruke> porukeList;
    @JoinColumn(name = "korisnici_id", referencedColumnName = "id")
    @ManyToOne(optional = false)
    private Korisnici korisniciId;

    public Ucitelji() {
    }

    public Ucitelji(Integer id) {
        this.id = id;
    }

    public Ucitelji(Integer id, String ime, String prezime) {
        this.id = id;
        this.ime = ime;
        this.prezime = prezime;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getIme() {
        return ime;
    }

    public void setIme(String ime) {
        this.ime = ime;
    }

    public String getPrezime() {
        return prezime;
    }

    public void setPrezime(String prezime) {
        this.prezime = prezime;
    }

    @XmlTransient
    public List<Odeljenja> getOdeljenjaList() {
        return odeljenjaList;
    }

    public void setOdeljenjaList(List<Odeljenja> odeljenjaList) {
        this.odeljenjaList = odeljenjaList;
    }

    @XmlTransient
    public List<Poruke> getPorukeList() {
        return porukeList;
    }

    public void setPorukeList(List<Poruke> porukeList) {
        this.porukeList = porukeList;
    }

    public Korisnici getKorisniciId() {
        return korisniciId;
    }

    public void setKorisniciId(Korisnici korisniciId) {
        this.korisniciId = korisniciId;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (id != null ? id.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Ucitelji)) {
            return false;
        }
        Ucitelji other = (Ucitelji) object;
        if ((this.id == null && other.id != null) || (this.id != null && !this.id.equals(other.id))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "entities.Ucitelji[ id=" + id + " ]";
    }
    
}

SMS/src/java/managedBeans/DepartmentManagedBean.java
package managedBeans;

import business.sessionBeans.DepartmentSessionBeanLocal;
import entities.Odeljenja;
import java.io.Serializable;
import java.util.List;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

@ManagedBean(name = "departmentMB", eager = true)
@SessionScoped
public class DepartmentManagedBean implements Serializable {
    
    @EJB
    private DepartmentSessionBeanLocal departmentBean; 
    
    public List<Odeljenja> getDepartments() {
        return departmentBean.getAllDepartments();
    }
}

SMS/src/java/managedBeans/ParentManagedBean.java
package managedBeans;

import business.sessionBeans.ParentSessionBeanLocal;
import entities.Roditelji;
import java.io.Serializable;
import java.util.List;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

@ManagedBean(name = "parentsMB", eager = true)
@SessionScoped
public class ParentManagedBean implements Serializable{
    
    @EJB
    private ParentSessionBeanLocal parentsBean;

    public List<Roditelji> getAllParents() {
        
        return parentsBean.getAllParents();        
    }
}

SMS/src/java/managedBeans/StudentManagedBean.java
package managedBeans;

import business.sessionBeans.StudentSessionBeanLocal;
import entities.Ucenici;
import java.io.Serializable;
import java.util.List;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

@ManagedBean(name = "studentMB", eager = true)
@SessionScoped
public class StudentManagedBean implements Serializable{
    
    @EJB
    private StudentSessionBeanLocal studentBean;
    
    public List<Ucenici> getAllStudents() {
        
        return studentBean.getAllStudents();
    }
        public List<Ucenici> getStudentsFromDepartment(int odeljenje) {
        
        return studentBean.getStudentsFromDepartment(odeljenje);
    }
}

SMS/web/Director.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        <h2>Lista odeljenja:</h2>
        <hr/>
        <h:form>
            <h:dataTable id= "odeljenjaId" value= "#{directorMB.departments}" var= "odeljenje">
                <h:column>
                    <f:facet name="header">Učitelj</f:facet>
                        #{odeljenje.uciteljiId.ime} #{odeljenje.uciteljiId.prezime}&#160;&#160;&#160;&#160;&#160;&#160;
                </h:column>
                <h:column>
                    <f:facet name="header">Odeljenje</f:facet> 
                        #{odeljenje.ime}&#160;&#160;&#160;&#160;&#160;&#160;
                </h:column>
                <h:column>
                    <f:facet name="header">Izmena</f:facet>
                    <h:commandButton value='Izmeni'/>
                </h:column>
            </h:dataTable>
        </h:form>
    </h:body>
</html>

SMS/web/adminDepartments.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Admin - Departments Manager</title>
    </h:head>
    <h:body>
        <h2>Lista odeljenja:</h2>
        <hr/>
        <h:form>
            <h:dataTable id= "odeljenjaId" value= "#{departmentMB.departments}" var= "odeljenje">
                <h:column>
                    <f:facet name="header">Učitelj</f:facet>
                        #{odeljenje.uciteljiId.ime} #{odeljenje.uciteljiId.prezime}&#160;&#160;&#160;&#160;&#160;&#160;
                </h:column>
                <h:column>
                    <f:facet name="header">Odeljenje</f:facet> 
                        #{odeljenje.ime}&#160;&#160;&#160;&#160;&#160;&#160;
                </h:column>
                <h:column>
                    <f:facet name="header">Izmena</f:facet>
                    <h:commandButton value='Izmeni'/>
                </h:column>
            </h:dataTable>
        </h:form>
    </h:body>
</html>

SMS/web/director.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        <h2>Lista odeljenja:</h2>
        <hr/>
        <h:form>
            <h:dataTable id= "odeljenjaId" value= "#{directorMB.departments}" var= "odeljenje">
                <h:column>
                    <f:facet name="header">Učitelj</f:facet>
                        #{odeljenje.uciteljiId.ime} #{odeljenje.uciteljiId.prezime}&#160;&#160;&#160;&#160;&#160;&#160;
                </h:column>
                <h:column>
                    <f:facet name="header">Odeljenje</f:facet> 
                        #{odeljenje.ime}&#160;&#160;&#160;&#160;&#160;&#160;
                </h:column>
                <h:column>
                    <f:facet name="header">Izmena</f:facet>
                    <h:commandButton value='Izmeni'/>
                </h:column>
            </h:dataTable>
        </h:form>
    </h:body>
</html>

SMS/web/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://xmlns.jcp.org/jsf/passthrough">
    <h:head>
        <title>Elektronski dnevnik - Prijava</title>
    </h:head>
    <h:body>
        <div name="login">
            <h2>Elektronski dnevnik - Prijava</h2>
            <hr/>
            <div name="logIn">
                <h:form>
                    <h:panelGrid id = "prijava" columns = "3" cellpadding = "10" cellspacing = "1">
                        <h:outputLabel value = "Korisničko ime:" />
                        <h:inputText id="korIme" required="true" p:placeholder="Nalog" requiredMessage="Polje je obavezno!" value="#{loginMB.username}" />
                        <h:message for="korIme" />

                        <h:outputLabel value = "Lozinka:" />
                        <h:inputSecret id="lozinka" required="true" p:placeholder="Lozinka" requiredMessage="Polje je obavezno!" value="#{loginMB.password}" />
                        <h:message for="lozinka" />
                    </h:panelGrid>
                
                    <h:panelGrid id = "user" columns = "5" cellpadding = "10" cellspacing = "1">
                        <h:selectOneRadio id="radio" required="true" requiredMessage="Prijavljujete se kao?" value="#{loginMB.user}">
                            <f:selectItem itemLabel="Admin" itemValue="0"/>
                            <f:selectItem itemLabel="Direktor" itemValue="1"/>
                            <f:selectItem itemLabel="Učitelj" itemValue="2"/>
                            <f:selectItem itemLabel="Roditelj" itemValue="3"/>
                        </h:selectOneRadio>
                        <h:message for="radio" />
                    </h:panelGrid>   
                    <h:outputLabel value="#{loginMB.message}" />
                    <div name="footerLogin">
                        <h:panelGrid>
                            <f:facet name="footer">
                                <h:commandButton id = "prijaviSe" value = "Prijavi se" action="#{loginMB.login()}" />    
                            </f:facet>
                        </h:panelGrid>
                    </div> 
                </h:form>
                <h:form>
                    <h:link value="Registracija" outcome="register"/>
                </h:form>
            </div>
        </div>
    </h:body>
</html>

SMS/web/poruke.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <title>Poruke</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </head>
    <body>
        <div>TODO write content</div>
    </body>
</html>

SMS/web/register.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://xmlns.jcp.org/jsf/passthrough">
    <h:head>
        <title>Elektronski dnevnik - Registracija</title>
    </h:head>
    <h:body>
        <h:form>
            <h:commandButton id="register" value="Registracija">
                <f:ajax render="registracijaId"/>
            </h:commandButton>&#160;&#160;
            <h:commandButton id="odeljenja" value = "Odeljenja">
                <f:ajax render="odeljenjaId"/>
            </h:commandButton>&#160;&#160;
            <h:commandButton id="ucenici" value = "Učenici">
                <f:ajax render="uceniciId"/>
            </h:commandButton>&#160;&#160;
            <h:commandButton id="roditelji" value = "Roditelji">
                <f:ajax render="roditeljiId"/>
            </h:commandButton>
         </h:form>
        <br/>
        
        <h2>Elektronski dnevnik - Registracija</h2>
        <hr/>
        <h:form>
            <h:panelGrid id = "registracijaId" columns = "3" cellpadding = "10" cellspacing = "1">
                <h:outputLabel value = "Ime:" />
                <h:inputText id="ime" required="true" p:placeholder="Ime" requiredMessage="Polje je obavezno!" value="" />
                <h:message for="ime" />
                
                <h:outputLabel value = "Prezime:" />
                <h:inputSecret id="prezime" required="true" p:placeholder="Prezime" requiredMessage="Polje je obavezno!" value="" />
                <h:message for="prezime" />
                
                <h:outputLabel value = "Nalog:" />
                <h:inputText id="nalog" required="true" p:placeholder="Nalog" requiredMessage="Polje je obavezno!" value="" />
                <h:message for="nalog" />
                
                <h:outputLabel value = "Lozinka:" />
                <h:inputSecret id="lozinka" required="true" p:placeholder="Lozinka" requiredMessage="Polje je obavezno!" value="" />
                <h:message for="lozinka" />
            </h:panelGrid>
        </h:form>
        <h:form>
            <h:panelGrid id = "user" columns = "5" cellpadding = "10" cellspacing = "1">
                <h:selectOneRadio id="radio" required="true" requiredMessage="Obavezno izabrati korisnika!" value="#">
                    <f:selectItem itemLabel="Admin" itemValue="0"/>
                    <f:selectItem itemLabel="Direktor" itemValue="1"/>
                    <f:selectItem itemLabel="Učitelj" itemValue="2"/>
                    <f:selectItem itemLabel="Roditelj" itemValue="3"/>
                </h:selectOneRadio>
                <h:message for="radio" />
            </h:panelGrid>
        </h:form>   
        <h:form>
                <div name="footerRegister">
                    <h:panelGrid>
                        <f:facet name="footer">
                        <h:commandButton id="registrujSe" value="Registruj" action="#" />
                        </f:facet>
                    </h:panelGrid>
                </div>   
        </h:form>
        <br/>
        
        <h2>Lista odeljenja:</h2>
        <hr/>
        <h:form>
            <h:dataTable id= "odeljenjaId" value= "#{departmentMB.departments}" var= "odeljenje">
                <h:column>
                    <f:facet name="header">Učitelj</f:facet>
                        #{odeljenje.uciteljiId.ime} #{odeljenje.uciteljiId.prezime}&#160;&#160;&#160;&#160;&#160;&#160;
                </h:column>
                <h:column>
                    <f:facet name="header">Odeljenje</f:facet> 
                        #{odeljenje.ime}&#160;&#160;&#160;&#160;&#160;&#160;
                </h:column>
                <h:column>
                    <f:facet name="header">Izmena</f:facet>
                    <h:commandButton value='Izmeni'/>
                </h:column>
            </h:dataTable>
        </h:form>
        <br/>
        
        <h2>Lista ucenika:</h2>
        <hr/>
        <h:form>
            <h:dataTable id = "uceniciId" value="#{studentMB.allStudents}" var="ucenici">
                <h:column>
                    <f:facet name="header">Učenik</f:facet>
                        #{ucenici.ime} #{ucenici.prezime}&#160;&#160;&#160;&#160;&#160;&#160;
                </h:column>
                <h:column>    
                    <f:facet name="header">Odeljenje</f:facet>
                        #{ucenici.odeljenjaId.ime}&#160;&#160;&#160;&#160;&#160;&#160;
                </h:column>
                <h:column>   
                    <f:facet name="header">Roditelj</f:facet>
                        #{ucenici.roditeljiId.ime} #{ucenici.roditeljiId.prezime}
                </h:column>
            </h:dataTable>
        </h:form>
        <br/>
        
        <h2>Lista roditelja:</h2>
        <hr/>
        <h:form>
            <h:dataTable id = "roditeljiId" value="#{parentsMB.allParents}" var="roditelji">
                <h:column>
                    <f:facet name="header">Roditelj</f:facet>
                        #{roditelji.ime} #{roditelji.prezime}&#160;&#160;&#160;&#160;&#160;&#160;
                </h:column>
                <h:column>    
                    <f:facet name="header">Nalog</f:facet>
                        #{roditelji.korisniciId.nalog}&#160;&#160;&#160;&#160;&#160;&#160;
                </h:column>
                <h:column>   
                    <f:facet name="header">Loznka</f:facet>
                       #{roditelji.korisniciId.lozinka}
                </h:column>
            </h:dataTable>
        </h:form>
        <br/>
        <h:form>
            <h:link value="Prijava" outcome="index"/>
        </h:form>
    </h:body>
</html>

SMS/web/uceniciOdeljenja.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <head>
        <title>TODO supply a title</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </head>
    <body>
            <h2>Lista ucenika:</h2>
        <hr/>
        <h:form>
            <h:dataTable id = "uceniciId" value="#{studentMB.getAllStudentsFromDepartment(1)}" var="ucenici">
                <h:column>
                    <f:facet name="header">Učenik</f:facet>
                                <h:commandButton id="uceniciId" value = "#{ucenici.ime} #{ucenici.prezime}"/>    
                </h:column>
            </h:dataTable>
        </h:form>
    </body>
</html>

SMS/web/ucenik.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <title>Ucenik</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </head>
    <body>
        
    </body>
</html>

SMS/web/ucitelji.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <head>
        <title>TODO supply a title</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </head>
    <body>
            <h2>Lista ucenika:</h2>
        <hr/>
        <h:form>
            <h:dataTable id = "uceniciId" value="#{studentMB.getStudentsFromDepartment(1)}" var="ucenici">
                <h:column>
                    <f:facet name="header">Učenik</f:facet>
                    #{ucenici.ime}
                    #{ucenici.prezime}
                </h:column>
                <h:column>    
                    <f:facet name="header">Odeljenje</f:facet>
                    #{ucenici.odeljenjaId.ime}
                </h:column>
                <h:column>   
                    <f:facet name="header">Roditelj</f:facet>
                    #{ucenici.odeljenjaId.id}
                </h:column>
            </h:dataTable>
        </h:form>
    </body>
</html>